### ISSUE TITLE
JBERET000007 - The instance was not associated with this session

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#1]
During the development, I use the method `Session#getIdentifier()` to obtain the identifier of the entity class `Address`. This is written in my item processor `AddressProcessor` as below : 

```java
Serializable id = session.getIdentifier(address);
```

However, I met the follow issue : 

```log
16:22:02,873 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 67) WFLYUT0021: Registered web context: /us-address
16:22:02,905 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "us-address.war" (runtime-name : "us-address.war")
16:22:03,053 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
16:22:03,053 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
16:22:03,054 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) started in 14170ms - Started 464 of 732 services (383 services are lazy, passive or on-demand)
16:22:51,437 ERROR [org.jberet] (Batch Thread - 1) ProcessingInfo{count=1, timerExpired=false, itemState=RUNNING, chunkState=RUNNING, checkpointPosition=-1, readPosition=0, failurePoint=null}
16:22:51,445 ERROR [org.jberet] (Batch Thread - 1) item-count=200, time-limit=0, skip-limit=-1, skipCount=0, retry-limit=-1, retryCount=0
16:22:51,445 ERROR [org.jberet] (Batch Thread - 1) JBERET000007: Failed to run job print-addresses-job, step1, org.jberet.job.model.Chunk@2fc11453: org.hibernate.TransientObjectException: The instance was not associated with this session
	at org.hibernate.internal.SessionImpl.getIdentifier(SessionImpl.java:1557)
	at io.github.mincongh.batch.AddressProcessor.processItem(AddressProcessor.java:84)
	at org.jberet.runtime.runner.ChunkRunner.processItem(ChunkRunner.java:403)
	at org.jberet.runtime.runner.ChunkRunner.readProcessWriteItems(ChunkRunner.java:309)
	at org.jberet.runtime.runner.ChunkRunner.run(ChunkRunner.java:201)
	at org.jberet.runtime.runner.StepExecutionRunner.runBatchletOrChunk(StepExecutionRunner.java:219)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:140)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:88)
	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:59)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

16:22:52,109 INFO  [stdout] (EJB default - 1) Finished
```

Maybe the input session is different from the standard class `org.hibernate.Session` ?

**Comment by mincong-h** [comment]
Ah, the `address` used is not in that `session` !!

**Comment by mincong-h** [comment]
Session will be closed when transaction is finished. So the identifier should be got in method `AddressReader#open()`, instead of method `AddressProcessor#process()`. All elements around the entities should be prepared in `AddressReader` or a context class, then be accessed by `AddressProcessor`

**Comment by mincong-h** [comment]
Operations related to the hibernate session have been moved to item reader `AddressReader`, so that they're called before the session closure.
