### ISSUE TITLE
Misc. improvements

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#133]
@mincong-h Feel free to split up this one into several issues as you address them. Creating this combined one for the sake of simplicity right now ;)
- [x] Add comment to PartitionAnalyzer
- [x] Use more specific names for PartitionAnalyzer, -Collector etc.; what are they doing?
- [x] BeforeChunkBatchlet shouldn't depend on the existing mass indexer; rather user `FullTextSession#purgeAll()`; same for `AfterChunkBatchlet`
- [x] Do we need PowerMock _and_ Mockito? It'd be nice to converge on one, preferably the latter
- [ ] Do we need both properties, _isJavaSE_ and _entityManagerFactory_? Isn't setting the latter indicating the former is true? Your comment on the prop seems to suggest that.
- [ ] What's the purpose of `MassIndexer#jobOperator()`? Couldn't it obtained locally via that static method BatchRuntime.getJobOperator()?
- [x] Reconsider interface/implementation split for `MassIndexer`; not sure what is gained, couldn't `MassIndexer` just be a class itself?
- [x] `RowComparator`/`StringComparator` seem unused
- [ ] Address TODO about tenant id in `ItemProcessor#buildAddLuceneWork(Object, Class<?>)`

**Comment by mincong-h** [comment]
Hi @gunnarmorling, I didn't understand the 3rd point: do you mean we shouldn't include the _PURGE_ operation in the mass indexer job ?

**Comment by gunnarmorling** [comment]
No, it should do the purging (if configured so by the user), but this should not be done via the existing mass indexer, but rather through that method on FTS. There should be no dependency between the existing MI and your new batch job.

**Comment by mincong-h** [comment]
Understood. Thx.

**Comment by mincong-h** [comment]
I use PowerMock and Mockito because I need to [Mocking static methods with Mockito][so], so the PowerMockito is used on the top of Mockito. More precisely, the static class to mock is [ContextHelper][1], which helps to obtain the identifier name.


[1]: https://github.com/mincong-h/gsoc-hsearch/blob/master/core/src/test/java/org/hibernate/search/jsr352/PartitionMapperTest.java#L53
[so]: http://stackoverflow.com/questions/21105403/mocking-static-methods-with-mockito

**Comment by mincong-h** [comment]
Hi @gunnarmorling,

> What's the purpose of MassIndexer#jobOperator()? Couldn't it obtained locally via that static method BatchRuntime.getJobOperator()?

In Java SE, the method `BatchRuntime.getJobOperator()` can only be used once. Otherwise, it throws error : 

```
java.util.ServiceConfigurationError: javax.batch.operations.JobOperator: Provider org.jberet.operations.JobOperatorImpl could not be instantiated
    at org.jboss.weld.environment.se.WeldContainer.initialize(WeldContainer.java:136)
    at org.jboss.weld.environment.se.Weld.initialize(Weld.java:589)
    at org.jberet.se.SEArtifactFactory.<init>(SEArtifactFactory.java:29)
    at org.jberet.se.BatchSEEnvironment.getArtifactFactory(BatchSEEnvironment.java:118)
    at org.jberet.operations.JobOperatorImpl.<init>(JobOperatorImpl.java:93)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at javax.batch.runtime.BatchRuntime.getJobOperator(BatchRuntime.java:57)
    at org.hibernate.search.jsr352.MassIndexerImpl.start(MassIndexerImpl.java:76)
    at org.hibernate.search.jsr352.se.MassIndexerIT.indexCompany(MassIndexerIT.java:108)
    at org.hibernate.search.jsr352.se.MassIndexerIT.testMassIndexer(MassIndexerIT.java:79)
```

This problem is described in issue #63 Test on Java SE, comment n°3. That's why I need to keep the `jobOperator(...)` for Java SE user.

> Do we need both properties, isJavaSE and entityManagerFactory? Isn't setting the latter indicating the former is true? Your comment on the prop seems to suggest that.

So far, there're two methods which are specific to Java SE : `entityManagerFactory(...)` and `jobOperator(...)`. In order to clarify the situation, I add the 3rd method `isJavaSE(...)`.

**Comment by mincong-h** [comment]
- [ ] I don't know what `OptimizeLuceneWork` is doing and therefore, I don't know how to modify it in `BeforeChunkBatchlet` and `AfterChunkBatchlet`.
- [ ] More TODOs here ...

These should be discussed at the next meeting

**Comment by gunnarmorling** [comment]
>  I don't know how to modify it in BeforeChunkBatchlet and AfterChunkBatchlet

You should be able to simply call `SearchFactory#optimize()` instead. And on `FullTextSession` you'll find `flushToIndexes()` and `purge()`. This should avoid all the calls to the existing mass indexer.

**Comment by yrodiere** [comment]
All items seem to have been addressed, to be obsolete or to be in the scope of a different issue.

Closing, feel free to reopen if you disagree.
