### ISSUE TITLE
Step config causes java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#19]
The java `java.lang.OutOfMemoryError` was thrown when asking the mass indexer to index the whole database with 3M+ entities : 

```
00:34:31,670 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 1) WFLYCTL0013: Operation ("read-attribute") failed - address: ([("deployment" => "us-address.war")]): java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.listIterator(ArrayList.java:823)
	at java.util.AbstractList.equals(AbstractList.java:518)
	at java.util.Collections$UnmodifiableList.equals(Collections.java:1306)
	at org.jboss.as.controller.PathAddress.equals(PathAddress.java:433)
	at org.jboss.as.controller.AbstractOperationContext$OperationId.equals(AbstractOperationContext.java:1437)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940)
	at org.jboss.as.controller.OperationContextImpl.authorize(OperationContextImpl.java:1704)
	at org.jboss.as.controller.OperationContextImpl.authorize(OperationContextImpl.java:1263)
	at org.jboss.as.controller.OperationContextImpl.authorize(OperationContextImpl.java:1253)
	at org.jboss.as.controller.operations.global.ReadAttributeHandler$AuthorizeAttributeReadHandler.doExecuteInternal(ReadAttributeHandler.java:222)
	at org.jboss.as.controller.operations.global.ReadAttributeHandler$AuthorizeAttributeReadHandler.execute(ReadAttributeHandler.java:207)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1344)
	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:392)
	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:204)
	at org.jboss.as.controller.ModelControllerImpl$3.execute(ModelControllerImpl.java:659)
	at org.jboss.as.controller.ModelControllerImpl$3.execute(ModelControllerImpl.java:649)
	at org.jboss.as.server.deployment.scanner.DefaultDeploymentOperations.getDeploymentsStatus(DefaultDeploymentOperations.java:76)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$ScanContext.<init>(FileSystemDeploymentService.java:1614)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$ScanContext.<init>(FileSystemDeploymentService.java:1563)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:568)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:489)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$DeploymentScanRunnable.run(FileSystemDeploymentService.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Here's the status of CPUs : 

<img width="1310" alt="screen shot 2016-06-05 at 00 36 24" src="https://cloud.githubusercontent.com/assets/10179217/15802546/10eaab36-2ab6-11e6-81bf-cc799bb0b0a6.png">

**Comment by mincong-h** [comment]
According to the discussion with @gunnarmorling this Monday, the problem is probably caused by the design of IDs queue: 

* In the current implementation of Hibernate Search, the IDs queue is small. ID producers produce IDs and add them into the queue. In the same time, ID consumers consume the queue, so that IDs stored in the queue stay in a low quantity.
* In this project, ID are still in queue. However, the consumers won't consume the IDs until the end of the IDs production. That's the main difference. So the number of ID stored can be huge.

There must be other factors that cause this issue too. But they won't be discussed here. Since the project design has been completely changed now, this tag will be marked as _wontfix_.
