### ISSUE TITLE
Cannot load transient user data from JobContext in step "produceLuceneDoc"

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#34]
The below line of code causes error : 

```java
long rowCount = (long) jobContext.getTransientUserData();
```

Here's the log : 

```log
00:57:09,216 INFO  [stdout] (default task-3) batchSession#printId() called
00:57:09,338 INFO  [stdout] (Batch Thread - 1) #mapPartitions(): 2 partitions.
00:57:09,339 INFO  [stdout] (Batch Thread - 1) #mapPartitions(): 2 partitions.
00:57:09,339 INFO  [stdout] (Batch Thread - 1) #getThreads(): 2 threads.
00:57:09,339 INFO  [stdout] (Batch Thread - 1) #mapPartitions(): 2 partitions.
00:57:09,339 INFO  [stdout] (Batch Thread - 1) #mapPartitions(): 2 partitions.
00:57:09,401 INFO  [stdout] (Batch Thread - 2) entityType = io.github.mincongh.entity.Address (3221316 rows).
00:57:09,401 INFO  [stdout] (Batch Thread - 3) entityType = io.github.mincongh.entity.Stock (4194 rows).
00:57:11,434 INFO  [stdout] (Batch Thread - 1) PurgeDecider#decide: purgeAtStart=true.
00:57:11,435 INFO  [stdout] (Batch Thread - 1) purging entities ...
00:57:11,436 INFO  [stdout] (Batch Thread - 1) AfterPurgeDecide#decide: true
00:57:11,437 INFO  [stdout] (Batch Thread - 1) Optimizing ...
00:57:11,439 INFO  [stdout] (Batch Thread - 1) #beginPartitionedStep() called.
00:57:11,441 INFO  [stdout] (Batch Thread - 1) #mapPartitions(): 5 partitions.
00:57:11,442 INFO  [stdout] (Batch Thread - 1) #getThreads(): 4 threads.
00:57:11,442 INFO  [stdout] (Batch Thread - 1) #mapPartitions(): 5 partitions.
00:57:11,450 INFO  [stdout] (Batch Thread - 4) BatchItemReader#open(io.github.mincongh.entity.Address)...
00:57:11,451 INFO  [stdout] (Batch Thread - 5) BatchItemReader#open(io.github.mincongh.entity.Address)...
00:57:11,452 INFO  [stdout] (Batch Thread - 6) BatchItemReader#open(io.github.mincongh.entity.Address)...
00:57:11,454 INFO  [stdout] (Batch Thread - 7) BatchItemReader#open(io.github.mincongh.entity.Address)...
00:58:11,547 INFO  [stdout] (Batch Thread - 6) BatchItemReader#close()
00:58:11,547 INFO  [stdout] (Batch Thread - 5) BatchItemReader#close()
00:58:11,550 INFO  [stdout] (Batch Thread - 8) BatchItemReader#open(io.github.mincongh.entity.Stock)...
00:58:11,550 INFO  [stdout] (Batch Thread - 8) BatchItemReader#close()
00:58:11,551 INFO  [stdout] (Batch Thread - 4) BatchItemReader#close()
00:58:11,551 ERROR [org.jberet] (Batch Thread - 1) JBERET000007: Failed to run job massIndex, produceLuceneDoc, org.jberet.job.model.Step@533507f4: java.lang.NullPointerException
	at io.github.mincongh.batch.LucenePartitionAnalyzer.analyzeCollectorData(LucenePartitionAnalyzer.java:40)
	at org.jberet.runtime.runner.StepExecutionRunner.beginPartition(StepExecutionRunner.java:376)
	at org.jberet.runtime.runner.StepExecutionRunner.runBatchletOrChunk(StepExecutionRunner.java:216)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:140)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:128)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:196)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:128)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runDecision(CompositeExecutionRunner.java:176)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:134)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:196)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:128)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runDecision(CompositeExecutionRunner.java:176)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:134)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:196)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:88)
	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:59)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

00:58:11,553 INFO  [stdout] (Batch Thread - 1) #rollbackPartitionedStep() called.
00:58:11,553 INFO  [stdout] (Batch Thread - 1) #afterPartitionedStepCompletion(...) called.
00:58:11,565 INFO  [stdout] (Batch Thread - 7) BatchItemReader#close()
```

**Comment by mincong-h** [comment]
According to the `JobContext` description in the page 77 of _JSR-352-1.0-Final-Release.pdf_ : 

> **JobContext**
> There is one `JobContext` per job execution. It exists for the life of a job. There is a distinct JobContext for each sub-thread of a parallel execution (e.g. partitioned step).

So for the [line 40][40] of `LucenePartitionAnalyzer`, I should rather avoid the standard tool `JobContext` and use the specific `io.github.mincongh.batch.IndexingContext` instead.

[40]: https://github.com/mincong-h/gsoc-hsearch/blob/9ccde4fa838eb434fa0681fd2189978ca560f5a1/us-address/src/main/java/io/github/mincongh/batch/LucenePartitionAnalyzer.java#L40
