### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#6]
```log
00:10:39,732 INFO  [stdout] (default task-2) batchSession#printId() called
00:11:43,872 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 1) WFLYCTL0013: Operation ("read-children-resources") failed - address: ([]): java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.security.AccessControlContext.combine(AccessControlContext.java:673)
	at java.security.AccessControlContext.optimize(AccessControlContext.java:628)
	at java.security.AccessController.getContext(AccessController.java:826)
	at org.jboss.as.controller.SecurityActions.getCaller(SecurityActions.java:47)
	at org.jboss.as.controller.AbstractOperationContext.getCaller(AbstractOperationContext.java:1138)
	at org.jboss.as.controller.OperationContextImpl.authorize(OperationContextImpl.java:1670)
	at org.jboss.as.controller.OperationContextImpl.readResourceFromRoot(OperationContextImpl.java:838)
	at org.jboss.as.controller.OperationContextImpl.readResource(OperationContextImpl.java:823)
	at org.jboss.as.controller.operations.global.ReadChildrenResourcesHandler.execute(ReadChildrenResourcesHandler.java:93)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1344)
	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:392)
	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:204)
	at org.jboss.as.controller.ModelControllerImpl$3.execute(ModelControllerImpl.java:659)
	at org.jboss.as.controller.ModelControllerImpl$3.execute(ModelControllerImpl.java:649)
	at org.jboss.as.server.deployment.scanner.DefaultDeploymentOperations.getDeploymentsStatus(DefaultDeploymentOperations.java:76)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$ScanContext.<init>(FileSystemDeploymentService.java:1614)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$ScanContext.<init>(FileSystemDeploymentService.java:1563)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:568)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:489)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$DeploymentScanRunnable.run(FileSystemDeploymentService.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

00:11:43,873 WARN  [org.jboss.jca.core.connectionmanager.listener.TxConnectionListener] (Batch Thread - 1) IJ000305: Connection error occured: org.jboss.jca.core.connectionmanager.listener.TxConnectionListener@18e06e35[state=NORMAL managed connection=org.jboss.jca.adapters.jdbc.local.LocalManagedConnection@533c23c4 connection handles=1 lastReturned=1464300625842 lastValidated=1464300625780 lastCheckedOut=1464300639827 trackByTx=false pool=org.jboss.jca.core.connectionmanager.pool.strategy.OnePool@1142953c mcp=SemaphoreConcurrentLinkedQueueManagedConnectionPool@349d8797[pool=MySqlDS-addresses] xaResource=LocalXAResourceImpl@4910f1ca[connectionListener=18e06e35 connectionManager=7b00c92f warned=false currentXid=null productName=MySQL productVersion=5.7.12 jndiName=java:/MySqlDS-addresses] txSync=null]: javax.resource.spi.ResourceAdapterInternalException: Unexpected error
	at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.broadcastConnectionError(BaseWrapperManagedConnection.java:684)
	at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.connectionError(BaseWrapperManagedConnection.java:650)
	at org.jboss.jca.adapters.jdbc.WrappedConnection.checkException(WrappedConnection.java:1964)
	at org.jboss.jca.adapters.jdbc.WrappedStatement.checkException(WrappedStatement.java:1446)
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:509)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2116)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1899)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1875)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2611)
	at org.hibernate.loader.Loader.doList(Loader.java:2594)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2423)
	at org.hibernate.loader.Loader.list(Loader.java:2418)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1774)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:385)
	at io.github.mincongh.batch.IdProducerBatchlet.process(IdProducerBatchlet.java:50)
	at org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:72)
	at org.jberet.runtime.runner.StepExecutionRunner.runBatchletOrChunk(StepExecutionRunner.java:222)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:140)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:88)
	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:59)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2157)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1964)
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3316)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:463)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3040)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2288)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2681)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:504)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2116)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1899)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1875)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2611)
	at org.hibernate.loader.Loader.doList(Loader.java:2594)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2423)
	at org.hibernate.loader.Loader.list(Loader.java:2418)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1774)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:385)
	at io.github.mincongh.batch.IdProducerBatchlet.process(IdProducerBatchlet.java:50)
	at org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:72)
	at org.jberet.runtime.runner.StepExecutionRunner.runBatchletOrChunk(StepExecutionRunner.java:222)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:140)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:88)
	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:59)

00:11:43,886 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0012: Scan of /Users/mincong/Documents/wildfly-10.0.0.Final/standalone/deployments threw Exception: java.lang.RuntimeException: WFLYDS0036: Deployment model operation failed. WFLYCTL0158: Operation handler failed: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.jboss.as.server.deployment.scanner.DefaultDeploymentOperations.getDeploymentsStatus(DefaultDeploymentOperations.java:83)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$ScanContext.<init>(FileSystemDeploymentService.java:1614)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$ScanContext.<init>(FileSystemDeploymentService.java:1563)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:568)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:489)
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$DeploymentScanRunnable.run(FileSystemDeploymentService.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
```

**Comment by mincong-h** [comment]
I need to add `Projection` for the result loading, otherwise all entities will be loaded which leads to out-of-memory error.

```java
long totalCount = (long) session
    .createCriteria(Address.class)
    .setProjection(Projections.rowCount())
    .setCacheable(false)
    .uniqueResult();
```
