### ISSUE TITLE
CDI failed: Failed to create artifact with ref name idProducerBatchlet.

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#60]
During the integration test, there's an error 

```log
22:04:14,643 WARN  [org.jberet] (Batch Thread - 2) JBERET000001: Failed to run batchlet org.jberet.job.model.RefArtifact@470484bb: java.lang.IllegalStateException: JBERET000600: Failed to create artifact with ref name idProducerBatchlet.  Ensure CDI beans.xml is present and batch.xml, if any, is configured properly.
	at org.jberet.runtime.context.JobContextImpl.createArtifact(JobContextImpl.java:185)
	at org.jberet.runtime.runner.AbstractRunner.createArtifact(AbstractRunner.java:156)
	at org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:66)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.IllegalStateException: JBERET000600: Failed to create artifact with ref name idProducerBatchlet.  Ensure CDI beans.xml is present and batch.xml, if any, is configured properly.
	at org.jberet.creation.ArtifactFactoryWrapper.getClassFromBatchXmlOrClassLoader(ArtifactFactoryWrapper.java:65)
	at org.jberet.creation.ArtifactFactoryWrapper.create(ArtifactFactoryWrapper.java:41)
	at org.jberet.runtime.context.JobContextImpl.createArtifact(JobContextImpl.java:183)
	... 10 more
Caused by: java.lang.ClassNotFoundException: idProducerBatchlet from [Module "deployment.5a86719a-30e7-4e72-b864-f48e4353dd15.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at org.jberet.creation.ArtifactFactoryWrapper.getClassFromBatchXmlOrClassLoader(ArtifactFactoryWrapper.java:63)
	... 12 more
```

And it seems that the beans xml is not recognized by WF, so the CDI failed.

This is weird because the beans.xml exists : 

    Mincongs-MBP:gsoc-hsearch mincong$ find ./target -name *beans.xml
    ./target/hs-jsr352-5.6.0-SNAPSHOT/WEB-INF/beans.xml

**Comment by mincong-h** [comment]
2 seconds before the above log, there's another message : 

> 22:04:12,651 INFO  [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 5) WELD-000119: Not generating any bean definitions from org.hibernate.search.jsr352.internal.IdProducerBatchlet because of underlying class loading error: Type org.hibernate.criterion.Projection from [Module "deployment.5a86719a-30e7-4e72-b864-f48e4353dd15.war:main" from Service Module Loader] not found.  If this is unexpected, enable DEBUG logging to see the full error.

So the `org.hibernate.criterion.Projection` is not found ... Does it mean I need to add all project dependencies in IT class `DeploymentIT` via `addClasses(Class<?> ...)` or `addPackages(boolean, String)` ?
