### ISSUE TITLE
Test on Java SE

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#63]
* https://jberet.gitbooks.io/jberet-user-guide/content/set_up_jberet/
* http://www.mastertheboss.com/javaee/batch-api/running-batch-jobs-in-j2se-applications
* https://github.com/jberet/jsr352/tree/master/test-apps

And I need to separate the project into multiple modules : 

- [x] core
- [x] integrationtest/javase
- [x] integrationtest/wilfly

**Comment by mincong-h** [comment]
Java SE test failed on : 

```log
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.526 sec <<< FAILURE! - in org.hibernate.search.jsr352.se.MassIndexerIT
testSearch(org.hibernate.search.jsr352.se.MassIndexerIT)  Time elapsed: 0.309 sec  <<< ERROR!
java.lang.IllegalStateException: Unable to access CDI
	at javax.enterprise.inject.spi.CDI.current(CDI.java:65)
	at org.hibernate.search.jsr352.MassIndexerImpl.registrerRootEntities(MassIndexerImpl.java:196)
	at org.hibernate.search.jsr352.MassIndexerImpl.start(MassIndexerImpl.java:36)
	at org.hibernate.search.jsr352.se.MassIndexerIT.indexCompany(MassIndexerIT.java:98)
	at org.hibernate.search.jsr352.se.MassIndexerIT.testSearch(MassIndexerIT.java:70)

```

Due to 

```java
public class MassIndexerImpl implements MassIndexer {
    // ...
    public void registrerRootEntities(Set<Class<?>> rootEntities) {
        // ...
        int s = rootEntities.size();
        BeanManager bm = CDI.current().getBeanManager();          // /!\ error
        Bean<IndexingContext> bean = (Bean<IndexingContext>) bm
                .resolve(bm.getBeans(IndexingContext.class));
        IndexingContext indexingContext = bm
                .getContext(bean.getScope())
                .get(bean, bm.createCreationalContext(bean));
        Class<?>[] r = rootEntities.toArray(new Class<?>[s]);
        indexingContext.setRootEntities(r);
    }
}
```

Java SE need another approach.

**Comment by mincong-h** [comment]
For test entity, use `Company` instead of `Stock` and `Address`. `Company` contains only 2 fields: id and name. It should be much easier for testing and decreases the code complexity.

**Comment by mincong-h** [comment]
There's an error : 

```
java.util.ServiceConfigurationError: javax.batch.operations.JobOperator: Provider org.jberet.operations.JobOperatorImpl could not be instantiated
	at org.jboss.weld.environment.se.WeldContainer.initialize(WeldContainer.java:136)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:589)
	at org.jberet.se.SEArtifactFactory.<init>(SEArtifactFactory.java:29)
	at org.jberet.se.BatchSEEnvironment.getArtifactFactory(BatchSEEnvironment.java:118)
	at org.jberet.operations.JobOperatorImpl.<init>(JobOperatorImpl.java:93)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.batch.runtime.BatchRuntime.getJobOperator(BatchRuntime.java:57)
	at org.hibernate.search.jsr352.MassIndexerImpl.start(MassIndexerImpl.java:76)
	at org.hibernate.search.jsr352.se.MassIndexerIT.indexCompany(MassIndexerIT.java:108)
	at org.hibernate.search.jsr352.se.MassIndexerIT.testMassIndexer(MassIndexerIT.java:79)
```

This is due to [the line 76 of MassIndexImpl][1] : 

```java
JobOperator jobOperator = BatchRuntime.getJobOperator();
```

I've instantiated a job operator in the integration test and another job operator inside the mass indexer impl. Maybe in Java SE, the job operator can only be instantiated once (singleton pb) ? **So the solution is to instantiate the job operator in IT, then pass it to indexer via setter.** Please see the below commit for more detail.

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/75bcf3e5768e35c4453aaff0d0229e13974e22c0/core/src/main/java/org/hibernate/search/jsr352/MassIndexerImpl.java#L76

**Comment by mincong-h** [comment]
The basic Java SE version should work with all the assertions now. Enhancement will be reported as an other issue.
