### ISSUE TITLE
JBERET000001: Failed to run batchlet ... java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#65]
It seems that JBERET cannot find the entity type `Class<?> entityClazz` using the entity string `entityType`. And I'm sure the entity has been loaded before the start of mass indexer because JPA used it to find records successfully.

Class<?> entityClazz = Class.forName(entityType);

```
02:29:53,974 WARN  [org.jberet] (Batch Thread - 3) JBERET000001: Failed to run batchlet org.jberet.job.model.RefArtifact@2fc3085: java.lang.ClassNotFoundException: class org.hibernate.gsoc.jsr352.test.entity.Address from [Module "deployment.94d66f6a-4aa4-4ae7-b521-8a228f2e25b8.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.hibernate.gsoc.jsr352.internal.IdProducerBatchlet.process(IdProducerBatchlet.java:52)
	at org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:72)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

02:29:53,974 WARN  [org.jberet] (Batch Thread - 2) JBERET000001: Failed to run batchlet org.jberet.job.model.RefArtifact@3b6f79c: java.lang.ClassNotFoundException: class org.hibernate.gsoc.jsr352.test.entity.Stock from [Module "deployment.94d66f6a-4aa4-4ae7-b521-8a228f2e25b8.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.hibernate.gsoc.jsr352.internal.IdProducerBatchlet.process(IdProducerBatchlet.java:52)
	at org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:72)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
```

**Comment by mincong-h** [comment]
Classes in `src/test/java` cannot be found be classes in `src/main/java`, that makes sense : test classes must know about the application to test it, but the application shouldn ot know about the test class

**Comment by gunnarmorling** [comment]
It seems you are still testing with WildFly? As discussed, I'd recommend to
focus on Java SE for the time being.

**Comment by mincong-h** [comment]
I think I'm not that far with Java EE, that's why I keep working on it .. But I'll follow your advice and start Java SE very soon (maybe tonight or tomorrow)
