### ISSUE TITLE
javax.transaction.RollbackException: ARJUNA016102: The transaction is not active!

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#67]
00:04:08,024 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionAnalyzer] (Batch Thread - 1) 286500 works processed (98.2%).

00:04:08,024 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionAnalyzer] (Batch Thread - 1) analyzeStatus called.

00:04:08,108 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 6) checkpointInfo

00:04:08,140 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 6) close

00:04:08,140 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionAnalyzer] (Batch Thread - 1) 287500 works processed (98.6%).

00:04:08,140 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionAnalyzer] (Batch Thread - 1) 287500 works processed (98.6%).

00:04:08,140 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionAnalyzer] (Batch Thread - 1) analyzeStatus called.

00:04:08,140 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #beforePartitionedStepCompletion() called.

00:04:08,140 WARN  [com.arjuna.ats.arjuna] (Batch Thread - 1) ARJUNA012077: Abort called on already aborted atomic action 0:ffffc0a80137:41e9ef2d:576c5c83:14

00:04:08,150 ERROR [org.jberet] (Batch Thread - 1) JBERET000007: Failed to run job massIndex, produceLuceneDoc, org.jberet.job.model.Step@4ee6e102: javax.transaction.RollbackException: ARJUNA016102: The transaction is not active! Uid is 0:ffffc0a80137:41e9ef2d:576c5c83:14

at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1190)

at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:126)

at com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.commit(BaseTransactionManagerDelegate.java:89)

at org.jberet.runtime.runner.StepExecutionRunner.beginPartition(StepExecutionRunner.java:388)

at org.jberet.runtime.runner.StepExecutionRunner.runBatchletOrChunk(StepExecutionRunner.java:216)

at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:140)

at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)

at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:128)

at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:196)

at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)

at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:128)

at org.jberet.runtime.runner.CompositeExecutionRunner.runDecision(CompositeExecutionRunner.java:176)

at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:134)

at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:196)

at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)

at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:128)

at org.jberet.runtime.runner.CompositeExecutionRunner.runDecision(CompositeExecutionRunner.java:176)

at org.jberet.runtime.runner.CompositeExecutionRunner.runJobElement(CompositeExecutionRunner.java:134)

at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:196)

at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)

at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:88)

at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:59)

at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)

at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)

at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)

at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

at org.jboss.threads.JBossThread.run(JBossThread.java:320)

00:04:08,151 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #rollbackPartitionedStep() called.

00:04:08,151 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #afterPartitionedStepCompletion(...) called.

According to [JBossDeveloper][1] 

> Typically errors like this where a component (in this case the HornetQ JCA RA) tries to work with a transaction and is told, "The transaction is not active!" are caused by a transaction timeout.  When a transaction times out the transaction manager rolls it back asynchronously and then when a compontent tries to access the transaction again (e.g. to commit it or roll it back) it won't be able to according to the JTA spec.

[1]: https://developer.jboss.org/thread/195775?tstart=0

**Comment by mincong-h** [comment]
According to JSR352 v1.0 final release.pdf : 

> Chunk type check points are transactional. The batch runtime uses global transaction mode on the Java EE platform and local transaction mode on the Java SE platform. Global transaction timeout is configurable at step-level with a step-level property:
>
> * javax.transaction.global.timeout={seconds} - default is 180 seconds 
>
> Example:
```xml
<step id="MyGlobalStep">
  <properties>
    <property name="javax.transaction.global.timeout" value="600"/>
  </properties>
</step>
```

A similar issue was report to java net as Bug 6356, check here :  https://java.net/bugzilla/show_bug.cgi?id=6356

**Comment by mincong-h** [comment]
The problem persists ...
When I use command `mvn clean install`, sometime the code works, sometime it doesn't. The same error reproduces. However, 600 seconds should be more than enough because the job takes only 44 seconds to execute. In addition, I'm using the localhost. I don't what the problem is.

I'll take care of it later. Let's focus on H2 and embed dataset.

**Comment by mincong-h** [comment]
The transaction timeout is defined in the WildFly config `standalone-full-testqueues.xml`. Change in from 2 seconds to 300 seconds and everything works fine.
