### ISSUE TITLE
Redesign the chunk in the job "mass-index"

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#97]
Redesign request by @gunnarmorling 

>2016-07-05 22:36 GMT+02:00 Mincong Huang <mincong.h@gmail.com>:
>Hi Gunnar, please check my responses.
>Please let me know your opinion about it. I'll start working on tomorrow.

>>On Tue, Jul 5, 2016 at 5:54 PM, Gunnar Morling <gunnar@hibernate.org> wrote:
>>Hi Mincong,

>>I've thought a bit more about restartability (check points) and the partition mapping business currently happening. Also I've dived a bit more into the JSR 352 and I've come to realize that the scope of BatchItemReader probably should be a bit different.

>>Specifically, I think BatchItemReader (let's find a less generic name btw.) should return one item at a time, which then is converted into the equivalent AddLuceneWork by BatchItemProcessor. The idea behind the chunk design is that (reader + processor) run n times, and then the item writer runs once for the list of processed items.

>You're right. (reader + processor) runs N times and then writer runs once. Then the chunk repeats.
 
>>So here is what I suggest:

>>* Let the job begin with a partition mapping by entity type (one partition per entity type)
>>* Get rid of the id producer batchlet, but rather let BatchItemReader itself works on a ScrollableResults fetching all the entities of that type; Note that the select query must be ordered by id so you can implement restartability (i.e. the checkpoint will be the id of the last entity returned by the reader). So essentially the query should look like so: select * from my_entity where id > last_id_seen order by id.

>I think your argument makes sense. Because the id producer batchlet is not that simple to understand and I'm making a hole of technical debt with the IndexingContext. It might have the effect as the "Java EE debt" -- the hole got deeper and deeper. Finally, I spend a huge time to go out because nobody else understand. But there're still things to clarify :

>>  rather let BatchItemReader itself works on a ScrollableResults

>Do we use one transaction for scrolling all the results on method "#readItem()" ? The transaction might be closed on the next read.

Yes, all the items should be read in one transaction. Only that will guarantee a consistent read of all items. The TX timeout can be increased if needed.

>  select query must be ordered by id so you can implement restartability

>Not necessarily. Entity IDs are "products" to consume: all the consumed ids will be polled and un-consumed ones stay.
Un-consumed ones will be persisted before the job stop and be reused on restart.

I don't think we should persist all the ids, this might take up much space potentially. Instead we just should store the last processed one. For that, ordering is required, as otherwise running the query might return results in a different order, potentially causing items to be missed or run twice. We don't want to read all the entities into memory before starting to process them. But rather open the cursor/ScrollableResults on the entity and then process them as we go.
 
>When I say this, I don't mean ordering ID is bad, I just don't know how to handle cases when id's type is not integer. ("id > last_id" still works ?)

It works for numeric types and Strings, that should be fine for now. We may look into making this more flexible later on.

>And here's the new idea (short-term) :
>    1.  There's no IdProducerBatchlet
>    2.  Item reader load IDs when the method "#open(Serializable)" called
>        a. If this is the first start, launch a query projecting to all IDs of the select entity type. Store them in a queue.
>        b. If this is a restart, get back the IDs from checkpoint.
>    3.  Item reader reads entities via method "#readItem()"
>        a.  Each "read" consumes a bulk of IDs in the queue and use it to fetch entities" [1]
>        b.  Use rather "where id in (...)" then "where id > last_id" to provide the exact results
>    4.  Item processor produces Lucene works using the bulk of entities, given by the reader.
>    5.  Item writes do Lucene works when item-count reaches

That's not exactly what I had in mind :) Note that the item reader should read *entities*, not *ids*. I don't think that this separation makes really sense with the JSR 352 design. Also there should be no notion of queue, instead the item reader should hold on to the ScrollableResults and move it forward upon each call of read().

So here is how it should be, in some more depth:

* The batch is partitioned by entity type
* In each partition, the item reader opens a ScrollableResults for the entities of its type (again, not *ids*)
* The item reader returns one entity from each read
* The item processor processes a single item
* The item writer writes the Lucene documents for a list of items

>[1]:
>    Q: Why not one ID per item ?
>    A: Because it's rather a waste to get one entity per transaction.

>>This will make things much simpler and make the mass indexing batch adhere to the design principles of JSR 352. Also it will allow you to implement restartability more easily and you can remove all the queueing business from IndexingContext.

>Yes, I agree with you.
 
>>On the downside, it reduces parallelism (which I think is why you introduced the notion of queues and the working on lists of ids), as the entities of one type will be processed sequentially. But I think we can add the partioning for this back later on, once the other things I described above are in place.

>You've successfully guessed my initial propose. Yes, I can do that. We focus on only one thing each time. 
This allows us the review the code easily and build code with quality and robustness.

Regarding parallelising, I think we can add this later on again if the steps described above are in place. The idea would be to partition the entities of one type by a modulo of the id (assuming for now its a numeric id). So let's say we want 4 partitions, we'd take the id mod 4, and partition 1 would process remainder 0, partition 2 would process remainder 1 etc.

That would be the default partition mapping strategy. For other id types we'd have to provide a way to customize the partitioning scheme based on the actual id type/value (i.e. leaving this to the user of the batch job), but limiting on numeric id types is fine for now.

But let's focus on the re-design described above and making sure that the checkpoint mechanism works correctly. Then adding this partitioning scheme should be not too hard.

**Comment by mincong-h** [comment]
I asked a question on SO: [How to write a criteria or HQL for generic scrollable results in Hibernate?][1]

[1]: http://stackoverflow.com/questions/38232598/how-to-write-a-criteria-or-hql-for-generic-scrollable-results-in-hibernate

**Comment by mincong-h** [comment]
When the `ScrollableResults` fetching locates in the method `open(Serializable)` [line 122 to line 124][1], then it works fine. When the `ScrollableResults` fetching locates in the method `#readItem()`, [line 137 to line 144][2], then the below error raises :

[1]:  https://github.com/mincong-h/gsoc-hsearch/blob/d31442e285c10a3a24a96ac5baeb13152a5b12e0/core/src/main/java/org/hibernate/search/jsr352/internal/BatchItemReader.java#L122-L124
[2]:  https://github.com/mincong-h/gsoc-hsearch/blob/d31442e285c10a3a24a96ac5baeb13152a5b12e0/core/src/main/java/org/hibernate/search/jsr352/internal/BatchItemReader.java#L137-L144

```
02:08:47,856 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "9cec2183-bb91-4ae3-9b15-c5d75f6521ef.war" (runtime-name : "9cec2183-bb91-4ae3-9b15-c5d75f6521ef.war")
02:08:48,752 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #beginPartitionedStep() called.
02:08:48,753 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionMapper] (Batch Thread - 1) #mapPartitions(): 1 partitions.
02:08:48,753 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionMapper] (Batch Thread - 1) #getThreads(): 1 threads.
02:08:48,766 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) open reader for entityName=org.hibernate.search.jsr352.test.entity.Company
02:08:48,785 INFO  [org.hibernate.search.jsr352.internal.BatchItemWriter] (Batch Thread - 2) open(Seriliazable) called
02:08:48,793 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) Reading item ...
02:08:48,794 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Batch Thread - 2) SQL Error: 0, SQLState: null
02:08:48,794 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Batch Thread - 2) IJ031040: Connection is not associated with a managed connection: org.jboss.jca.adapters.jdbc.jdk7.WrappedConnectionJDK7@472de7db
02:08:48,798 ERROR [org.jberet] (Batch Thread - 2) ProcessingInfo{count=0, timerExpired=false, itemState=RUNNING, chunkState=RUNNING, checkpointPosition=-1, readPosition=0, failurePoint=null}
02:08:48,813 ERROR [org.jberet] (Batch Thread - 2) item-count=3, time-limit=0, skip-limit=-1, skipCount=0, retry-limit=-1, retryCount=0
02:08:48,813 ERROR [org.jberet] (Batch Thread - 2) JBERET000007: Failed to run job massIndex, produceLuceneDoc, org.jberet.job.model.Chunk@45d187d8: org.hibernate.exception.GenericJDBCException: could not advance using next()
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
	at org.hibernate.internal.ScrollableResultsImpl.convert(ScrollableResultsImpl.java:69)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:104)
	at org.hibernate.search.jsr352.internal.BatchItemReader.readItem(BatchItemReader.java:137)
	at org.jberet.runtime.runner.ChunkRunner.readItem(ChunkRunner.java:353)
	at org.jberet.runtime.runner.ChunkRunner.readProcessWriteItems(ChunkRunner.java:305)
	at org.jberet.runtime.runner.ChunkRunner.run(ChunkRunner.java:201)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.sql.SQLException: IJ031040: Connection is not associated with a managed connection: org.jboss.jca.adapters.jdbc.jdk7.WrappedConnectionJDK7@472de7db
	at org.jboss.jca.adapters.jdbc.WrappedConnection.lock(WrappedConnection.java:164)
	at org.jboss.jca.adapters.jdbc.WrappedStatement.lock(WrappedStatement.java:138)
	at org.jboss.jca.adapters.jdbc.WrappedResultSet.lock(WrappedResultSet.java:6022)
	at org.jboss.jca.adapters.jdbc.WrappedResultSet.next(WrappedResultSet.java:2679)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:99)
	... 12 more

02:08:48,816 INFO  [org.hibernate.search.jsr352.internal.BatchItemWriter] (Batch Thread - 2) close() called
02:08:48,816 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) closing ...
02:08:48,818 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionAnalyzer] (Batch Thread - 1) analyzeStatus called.
02:08:48,819 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #rollbackPartitionedStep() called.
02:08:48,819 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #afterPartitionedStepCompletion(...) called.
02:08:48,822 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) scrollable results closed.
```

**Comment by mincong-h** [comment]
I think a `StatelessSession` is needed before the creation of scrollable results, as indicated in the [Kohei Nozaki's blog][1].

[1]: http://www.nailedtothex.org/roller/kyle/entry/articles-jbatch-hibernate

**Comment by mincong-h** [comment]
After the code updated following article [Kohei Nozaki • Chunk-oriented Processing with Hibernate's StatelessSession][1], the code still failed. Here's the error : 

```log
21:08:58,671 INFO  [org.jboss.as.server] (management-handler-thread - 2) WFLYSRV0010: Deployed "517e9d76-d871-4e5c-b612-da076c301ab6.war" (runtime-name : "517e9d76-d871-4e5c-b612-da076c301ab6.war")
21:08:59,652 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #beginPartitionedStep() called.
21:08:59,653 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionMapper] (Batch Thread - 1) #mapPartitions(): 1 partitions.
21:08:59,653 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionMapper] (Batch Thread - 1) #getThreads(): 1 threads.
21:08:59,662 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) open reader for entityName=org.hibernate.search.jsr352.test.entity.Company
21:08:59,680 INFO  [org.hibernate.search.jsr352.internal.BatchItemWriter] (Batch Thread - 2) open(Seriliazable) called
21:08:59,684 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) Reading item ...
21:08:59,698 ERROR [org.jberet] (Batch Thread - 2) ProcessingInfo{count=1, timerExpired=false, itemState=RUNNING, chunkState=RUNNING, checkpointPosition=-1, readPosition=0, failurePoint=null}
21:08:59,709 ERROR [org.jberet] (Batch Thread - 2) item-count=3, time-limit=0, skip-limit=-1, skipCount=0, retry-limit=-1, retryCount=0
21:08:59,709 ERROR [org.jberet] (Batch Thread - 2) JBERET000007: Failed to run job massIndex, produceLuceneDoc, org.jberet.job.model.Chunk@3ee9beca: org.hibernate.TransientObjectException: The instance was not associated with this session
	at org.hibernate.internal.SessionImpl.getIdentifier(SessionImpl.java:1557)
	at org.hibernate.search.jsr352.internal.BatchItemProcessor.buildAddLuceneWork(BatchItemProcessor.java:140)
	at org.hibernate.search.jsr352.internal.BatchItemProcessor.processItem(BatchItemProcessor.java:95)
	at org.jberet.runtime.runner.ChunkRunner.processItem(ChunkRunner.java:403)
	at org.jberet.runtime.runner.ChunkRunner.readProcessWriteItems(ChunkRunner.java:309)
	at org.jberet.runtime.runner.ChunkRunner.run(ChunkRunner.java:201)
	at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:243)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

21:08:59,711 INFO  [org.hibernate.search.jsr352.internal.BatchItemWriter] (Batch Thread - 2) close() called
21:08:59,711 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) closing everything...
21:08:59,713 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) Scrollable results closed.
21:08:59,713 INFO  [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) Stateless session closed.
21:08:59,713 ERROR [org.hibernate.search.jsr352.internal.BatchItemReader] (Batch Thread - 2) org.hibernate.SessionException: Session was already closed
21:08:59,714 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionAnalyzer] (Batch Thread - 1) analyzeStatus called.
21:08:59,714 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #rollbackPartitionedStep() called.
21:08:59,714 INFO  [org.hibernate.search.jsr352.internal.LucenePartitionReducer] (Batch Thread - 1) #afterPartitionedStepCompletion(...) called.
21:13:00,523 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 71) WFLYUT0022: Unregistered web context: /517e9d76-d871-4e5c-b612-da076c301ab6
21:13:00,539 INFO  [org.jboss.weld.deployer] (MSC service thread 1-8) WFLYWELD0010: Stopping weld service for deployment 517e9d76-d871-4e5c-b612-da076c301ab6.war
```

[1]: http://www.nailedtothex.org/roller/kyle/entry/articles-jbatch-hibernate

**Comment by mincong-h** [comment]
@gunnarmorling had already mentioned this issue : 

> Regarding item processor, good point. We might be able to move all EM/session usage into the reader and writer.

I followed this idea and moved the processor logic into reader. After this change and some changes about the `EntityManager` handling in Java SE, everything works fine. So now, we can test the project again using 

    mvn clean install

**Comment by mincong-h** [comment]
@gunnarmorling, the error raised by `BatchItemProcessor` can be seen on above comment : 

> After the code updated following article Kohei Nozaki • Chunk-oriented Processing with Hibernate's StatelessSession, the code still failed. Here's the error [...]

More precisely here : 

```
21:08:59,709 ERROR [org.jberet] (Batch Thread - 2) JBERET000007: Failed to run job massIndex, produceLuceneDoc, org.jberet.job.model.Chunk@3ee9beca: org.hibernate.TransientObjectException: The instance was not associated with this session
    at org.hibernate.internal.SessionImpl.getIdentifier(SessionImpl.java:1557)
    at org.hibernate.search.jsr352.internal.BatchItemProcessor.buildAddLuceneWork(BatchItemProcessor.java:140)
    at org.hibernate.search.jsr352.internal.BatchItemProcessor.processItem(BatchItemProcessor.java:95)
```

And the error should be reproduced using the commit 21fe2ea, (I'm not 100% sure)

**Comment by mincong-h** [comment]
Use `entityIndexBinding.getDocumentBuilder().getIdentifierName();` to get identifier
